### ISSUE TITLE
Define LICENSE/ COPYING

### ISSUE THREAD

**Issue by dvzrv** [pure-data/pd-icon#1]
Hi, I'd like to use masters/icon.svg for packaging purposes on Arch Linux.
Can you please add a license statement for the files and data in this repositories, so others are allowed to use it?
Thanks!

**Comment by danomatika** [comment]
BTW I think the SVG that was used for the final version is `masters/icon_svgplugin_inkscape.svg`.

**Comment by danomatika** [comment]
Note: You will need to have DejaVu Sans Mono installed to render the font correctly in the SVG. If you just need to package things, perhaps it makes more sense to include the master 1024x1024 PNG in the main Pd repo. Then there will be no chance that packaging could end up with a slightly different icon due to a missing font.

**Comment by dvzrv** [comment]
> Note: You will need to have DejaVu Sans Mono installed to render the font correctly in the SVG.

That's not a problem :)

**Comment by danomatika** [comment]
I cleaned out the old masters, updated the readme, and added a BSD license. If you already have some scripting in place, you may need to adjust to reflect the base masters are "icon1024.png" and "icon.svg."

**Comment by dvzrv** [comment]
Thanks a lot!
